Set of changes updating version 8.2 to the level of 8.1, since 8.2 development had been halted since it was first created back in April. Version 8.2 is now the official development version, with the first development push to create a Cairo graphics interface.

diff --git a/scripts/configure.in b/scripts/configure.in
--- a/scripts/configure.in
+++ b/scripts/configure.in
@@ -28,20 +28,23 @@ AC_ISC_POSIX
 AC_PROG_INSTALL
 AC_PROG_RANLIB
 
-dnl GNU M4 is preferred due to some of the option switches.
-AC_PATH_PROGS([M4], [gm4 gnum4 m4], [no])
-if test x$M4 = xno; then
-  AC_MSG_ERROR([M4 is required])
-fi
+dnl Python3 is preferred for running the preprocessor script
+dnl but CPP can be used instead.
+AC_PATH_PROG([PYTHON3], [python3], [no])
+if test "x${PYTHON3}" == "x"; then
 
-dnl check size of pointer for correct behavior on 64-bit systems
-dnl If the C preprocessor is GCC, we need to force the flag to
-dnl assert that input files are of type C, or else the preprocessing
-dnl stage will not execute correctly on the ".in" files in the scmos
-dnl directory.
+   dnl check size of pointer for correct behavior on 64-bit systems
+   dnl If the C preprocessor is GCC, we need to force the flag to
+   dnl assert that input files are of type C, or else the preprocessing
+   dnl stage will not execute correctly on the ".in" files in the scmos
+   dnl directory.
 
-if test "$CPP" = "$CC -E" ; then
-   CPP="$CPP -x c"
+   if test "$CPP" = "$CC -E" ; then
+      CPP="$CPP -x c"
+   fi
+
+else
+   CPP="${MAGICDIR}/scripts/preproc.py"
 fi
 
 dnl check if the linker is a GNU linker
@@ -289,6 +292,7 @@ usingOGL=1
 use_libglu="-lGLU"
 usingTcl=1
 usingOA=0
+usingCairo=1
 
 dnl Check for gcore, used by niceabort.c
 
@@ -317,6 +321,10 @@ else
   if test $usingOGL ; then
     echo "Cannot use OpenGL/GLX without X11, disabling."
     usingOGL=
+  fi
+  if test $usingCairo ; then
+    echo "Cannot use Cairo without X11, disabling."
+    usingCairo=
   fi
   if test $usingTcl ; then
     echo "Cannot compile TCL version without X11, disabling."
@@ -1151,6 +1159,51 @@ if test $usingOGL ; then
 fi
 
 dnl ----------------------------------------------------------------
+dnl Check for cairo graphics headers and libraries
+dnl ----------------------------------------------------------------
+
+AC_ARG_WITH(cairo,
+[  --with-cairo=DIR          use Cairo include files in DIR], [
+  if test "$withval" = "no" -o "$withval" = "NO" ; then
+    usingCairo=
+  elif test "$withval" != "no" -a "$withval" != "yes"; then
+    CAIRO_INCLUDE_DIR=${withval}
+  fi
+])
+
+if test $usingCairo ; then
+    ac_save_CPPFLAGS="$CPPFLAGS"
+    if test $CAIRO_INCLUDE_DIR ; then
+        CPPFLAGS="$CPPFLAGS -I$CAIRO_INCLUDE_DIR"
+    fi
+    CPPFLAGS="$CPPFLAGS $X_CFLAGS"
+    AC_CHECK_HEADER(cairo/cairo.h, , [
+	echo "Cairo header files not found, disabling Cairo"
+	usingCairo= 
+    ],)
+    CPPFLAGS="$ac_save_CPPFLAGS"
+fi
+
+if test $usingCairo ; then
+    ac_save_CPPFLAGS="$CPPFLAGS"
+    ac_save_LDFLAGS="$LDFLAGS"
+    LDFLAGS="$LDFLAGS $X_LIBS $X_EXTRA_LIBS -lm"
+    AC_CHECK_LIB(cairo, cairo_user_to_device, , [
+	echo "Cairo library files not found, disabling Cairo"
+ 	usingCairo=
+    ],)
+    CPPFLAGS="$ac_save_CPPFLAGS"
+    LDFLAGS="$ac_save_LDFLAGS"
+fi
+
+if test $usingCairo ; then
+    if test $CAIRO_INCLUDE_DIR ; then
+	gr_cflags="${gr_cflags} -I${CAIRO_INCLUDE_DIR}"
+    fi
+fi
+
+
+dnl ----------------------------------------------------------------
 dnl Once we're sure what, if any, interpreter is being compiled,
 dnl set all the appropriate definitions.  For Tcl/Tk, override
 dnl the default install targets: allows compiling tcl version with
@@ -1194,6 +1247,16 @@ if test $usingTcl ; then
     AC_DEFINE(THREE_D)
     gr_dflags="$gr_dflags -DOGL"
     gr_libs="$gr_libs -lGL ${use_libglu} ${use_libxi} ${use_libxmu} ${use_libxext} -lm"
+    gr_srcs="$gr_srcs \${TOGL_SRCS}"
+    if ! test $usingX11 ; then
+      usingX11=1
+      gr_dflags="$gr_dflags -DXLIB"
+      gr_libs="$gr_libs -lX11"
+    fi
+  fi
+  if test $usingCairo ; then
+    gr_dflags="$gr_dflags -DCAIRO"
+    gr_libs="$gr_libs -lcairo -lfontconfig -lfreetype"
     gr_srcs="$gr_srcs \${TOGL_SRCS}"
     if ! test $usingX11 ; then
       usingX11=1
@@ -1737,6 +1800,20 @@ else
    echo "  files, which are usually available from the video card manufacturer."
    echo "  Magic with un-accelerated OpenGL, such as using Mesa GL without"
    echo "  a supported graphics card, is usually a very bad combination."
+   echo
+fi
+
+${ECHO_N} "Cairo:        "
+if test $usingCairo ; then
+   echo "yes"
+else
+   echo "no"
+   echo
+   echo "  Cairo graphics are considerably better than the standard 8-bit"
+   echo "  and 24-bit X11 graphics, provided that you have a video card and"
+   echo "  driver supporting hardware-accelerated graphics.  If you get this"
+   echo "  message, you may need to download Cairo and fontconfig libraries"
+   echo "  and header files, which are usually found in package cairo-devel."
    echo
 fi
 
